spring.application.name=notes4unical
spring.datasource.url=jdbc:postgresql://localhost:5432/notes4unical
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

